[build]
  builder = "DOCKERFILE"
  dockerfilePath = "Dockerfile"

[deploy]
  healthcheckPath = "/actuator/health"
  healthcheckInterval = 30

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
