services:
  - type: web
    name: flowerist-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_PASSWORD
        sync: false
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-morning-unit-as3jxork-pooler.c-4.eu-central-1.aws.neon.tech/neondb?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        fromEnvVar: DB_PASSWORD
    healthCheckPath: /actuator/health
    plan: free
